//
// Created by tjb3 on 8/22/16.
//

#ifndef HTGS_TASKGRAPHDOTGENFLAGS_HPP
#define HTGS_TASKGRAPHDOTGENFLAGS_HPP

#define DOTGEN_FLAG_HIDE_MEM_EDGES         1 << 0
#define DOTGEN_FLAG_SHOW_ALL_THREADING     1 << 1
#define DOTGEN_FLAG_SHOW_IN_OUT_TYPES      1 << 2
#define DOTGEN_FLAG_HIDE_PROFILE_COMP_TIME 1 << 3
#define DOTGEN_FLAG_HIDE_PROFILE_MAX_Q_SZ  1 << 4
#define DOTGEN_FLAG_HIDE_PROFILE_WAIT_TIME 1 << 5
#define DOTGEN_COLOR_COMP_TIME             1 << 6
#define DOTGEN_COLOR_MAX_Q_SZ              1 << 7
#define DOTGEN_COLOR_WAIT_TIME             1 << 8

#endif //HTGS_TASKGRAPHDOTGENFLAGS_HPP
