var annotated_dup =
[
    [ "htgs", null, [
      [ "AnyConnector", "classhtgs_1_1_any_connector.html", "classhtgs_1_1_any_connector" ],
      [ "AnyIRule", "classhtgs_1_1_any_i_rule.html", "classhtgs_1_1_any_i_rule" ],
      [ "AnyITask", "classhtgs_1_1_any_i_task.html", "classhtgs_1_1_any_i_task" ],
      [ "AnyMemoryAllocator", "classhtgs_1_1_any_memory_allocator.html", "classhtgs_1_1_any_memory_allocator" ],
      [ "AnyRuleManager", "classhtgs_1_1_any_rule_manager.html", "classhtgs_1_1_any_rule_manager" ],
      [ "AnyRuleManagerInOnly", "classhtgs_1_1_any_rule_manager_in_only.html", "classhtgs_1_1_any_rule_manager_in_only" ],
      [ "AnyTaskGraphConf", "classhtgs_1_1_any_task_graph_conf.html", "classhtgs_1_1_any_task_graph_conf" ],
      [ "AnyTaskManager", "classhtgs_1_1_any_task_manager.html", "classhtgs_1_1_any_task_manager" ],
      [ "BlockingQueue", "classhtgs_1_1_blocking_queue.html", "classhtgs_1_1_blocking_queue" ],
      [ "Bookkeeper", "classhtgs_1_1_bookkeeper.html", "classhtgs_1_1_bookkeeper" ],
      [ "Connector", "classhtgs_1_1_connector.html", "classhtgs_1_1_connector" ],
      [ "CudaMemoryManager", "classhtgs_1_1_cuda_memory_manager.html", "classhtgs_1_1_cuda_memory_manager" ],
      [ "DataPacket", "classhtgs_1_1_data_packet.html", "classhtgs_1_1_data_packet" ],
      [ "EdgeDescriptor", "classhtgs_1_1_edge_descriptor.html", "classhtgs_1_1_edge_descriptor" ],
      [ "ExecutionPipeline", "classhtgs_1_1_execution_pipeline.html", "classhtgs_1_1_execution_pipeline" ],
      [ "ExecutionPipelineBroadcastRule", "classhtgs_1_1_execution_pipeline_broadcast_rule.html", "classhtgs_1_1_execution_pipeline_broadcast_rule" ],
      [ "ICudaTask", "classhtgs_1_1_i_cuda_task.html", "classhtgs_1_1_i_cuda_task" ],
      [ "IData", "classhtgs_1_1_i_data.html", "classhtgs_1_1_i_data" ],
      [ "IMemoryAllocator", "classhtgs_1_1_i_memory_allocator.html", "classhtgs_1_1_i_memory_allocator" ],
      [ "IMemoryReleaseRule", "classhtgs_1_1_i_memory_release_rule.html", "classhtgs_1_1_i_memory_release_rule" ],
      [ "IRule", "classhtgs_1_1_i_rule.html", "classhtgs_1_1_i_rule" ],
      [ "ITask", "classhtgs_1_1_i_task.html", "classhtgs_1_1_i_task" ],
      [ "MemoryData", "classhtgs_1_1_memory_data.html", "classhtgs_1_1_memory_data" ],
      [ "MemoryEdge", "classhtgs_1_1_memory_edge.html", "classhtgs_1_1_memory_edge" ],
      [ "MemoryManager", "classhtgs_1_1_memory_manager.html", "classhtgs_1_1_memory_manager" ],
      [ "MemoryPool", "classhtgs_1_1_memory_pool.html", "classhtgs_1_1_memory_pool" ],
      [ "PriorityBlockingQueue", "classhtgs_1_1_priority_blocking_queue.html", "classhtgs_1_1_priority_blocking_queue" ],
      [ "ProducerConsumerEdge", "classhtgs_1_1_producer_consumer_edge.html", "classhtgs_1_1_producer_consumer_edge" ],
      [ "RuleEdge", "classhtgs_1_1_rule_edge.html", "classhtgs_1_1_rule_edge" ],
      [ "RuleManager", "classhtgs_1_1_rule_manager.html", "classhtgs_1_1_rule_manager" ],
      [ "StateContainer", "classhtgs_1_1_state_container.html", "classhtgs_1_1_state_container" ],
      [ "TaskGraphCommunicator", "classhtgs_1_1_task_graph_communicator.html", "classhtgs_1_1_task_graph_communicator" ],
      [ "TaskGraphConf", "classhtgs_1_1_task_graph_conf.html", "classhtgs_1_1_task_graph_conf" ],
      [ "TaskGraphProfiler", "classhtgs_1_1_task_graph_profiler.html", "classhtgs_1_1_task_graph_profiler" ],
      [ "TaskGraphRuntime", "classhtgs_1_1_task_graph_runtime.html", "classhtgs_1_1_task_graph_runtime" ],
      [ "TaskGraphSignalHandler", "classhtgs_1_1_task_graph_signal_handler.html", null ],
      [ "TaskManager", "classhtgs_1_1_task_manager.html", "classhtgs_1_1_task_manager" ],
      [ "TaskManagerProfile", "classhtgs_1_1_task_manager_profile.html", "classhtgs_1_1_task_manager_profile" ],
      [ "TaskManagerThread", "classhtgs_1_1_task_manager_thread.html", "classhtgs_1_1_task_manager_thread" ],
      [ "VoidData", "classhtgs_1_1_void_data.html", "classhtgs_1_1_void_data" ]
    ] ],
    [ "htgs_dbglog", "structhtgs__dbglog.html", null ],
    [ "htgs_lglog", "structhtgs__lglog.html", null ]
];